server:
  port: 8080
  error:
    include-message: always # Útil para debug local

spring:
  application:
    name: visao360-gateway

  datasource:
    # URL de conexão com o seu PostgreSQL local
    url: jdbc:postgresql://localhost:5432/primordial_db
    username: postgres
    password: sua_senha_super_secreta
    driver-class-name: org.postgresql.Driver
    
    # HikariCP: O nosso gerenciador de conexões. 
    # É ele que vamos "hackear" do bem para injetar o clinic_id do RLS.
    hikari:
      pool-name: PrimordialRLSPool
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Exibe o SQL no console para vermos a mágica do RLS acontecendo
    show-sql: true 
    hibernate:
      # 'update' atualiza as tabelas automaticamente no ambiente de dev. 
      # EM PRODUÇÃO, isso deve ser 'validate' ou 'none'.
      ddl-auto: update 
    properties:
      hibernate:
        format_sql: true