-- Arquivo legado mantido para compatibilidade documental.
-- Use db/postgres-ehr-teste-bridge.sql, que cria a persistência e o RLS no
-- contrato compatível com as tabelas normalizadas do schema ehr_teste.
